---
title: "potential_output"
author: "Ricardo Mayer"
date: "April 17, 2017"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(printr)
```

```{r, load_libraries, include=FALSE}
library(dplyr) # use dplyr::first and dplyr::last
library(ggplot2)
library(xts) # use xts::first and xts::last
library(tidyr)
library(lubridate)
library(tibble)
library(tidyquant)
library(ggthemes)
```

```{r load_principal_data, cache=TRUE, include=FALSE}
load("../produced_data/WEOApr2017_cepal_and_others")
```


```{r calculate_gaps_trends, include=FALSE}

source("../functions/funcs_for_new_normal.R")

subject_dict_co <- WEOApr2017cepal18_others_long %>% 
  filter(iso == "CHL" & year == 2000) %>% 
  select(-c(value, iso, country, country_series_specific_notes,
            weo_country_code, estimates_start_after, scale, year))

subject_dict_wo <- WEOApr2017cepal18_others_long %>% 
  filter(country == "World" & year == 2000) %>% 
  select(-c(value, iso,  country_series_specific_notes,
            weo_country_code, estimates_start_after, scale, year))

weo_few <- WEOApr2017cepal18_others_long %>% 
  select(iso, country, year, weo_subject_code, value) %>% 
  filter(weo_subject_code %in% c("NGDP_R", "NGDP_RPCH", "NGAP_NPGDP")) 

real_gdp_long <- weo_few %>% 
  filter(weo_subject_code %in% c("NGDP_R")) %>% 
  mutate(date =  ymd(paste0(year,  "-12-31"))) 

# foo <- add_ts_filters(real_gdp_long , date_colname = "date", value_colname = "value", country_colname = "iso")

real_gdp_hp <- add_ts_filters(real_gdp_long) %>% arrange(country, date) %>% 
  group_by(country) %>% 
  mutate(trend_growth_pct = 100*(hp_trend / dplyr::lag(hp_trend)-1)    )

trend_growth_2003_2008 <- real_gdp_hp %>% 
  filter(year>=2003 & year <= 2008) %>% 
  summarise(avg_tg_2003_2008 = mean(trend_growth_pct))

trend_growth_2010_2016 <- real_gdp_hp %>% 
  filter(year>=2010 & year <= 2016) %>% 
  summarise(avg_tg_2010_2016 = mean(trend_growth_pct))

trend_growth_2003_2008_2010_2016 <- left_join(trend_growth_2003_2008,
                                              trend_growth_2010_2016,
                                              by = "country") %>% 
  mutate(dif = avg_tg_2010_2016 - avg_tg_2003_2008 )


  
  
real_gdp_country_wide <- real_gdp_long %>% 
  spread(key = country, value=value)

real_gdp_growth_long <- weo_few %>% 
  filter(weo_subject_code %in% c("NGDP_RPCH"))


weo_long_EU_AE_G7 <- subset(weo_few , 
                country %in% c("Major advanced economies (G7)",
                               "Euro area " , "Advanced economies")) %>% 
  select(-iso) %>% arrange(country, year)

weo_cwide_EU_AE_G7 <- weo_long_EU_AE_G7 %>% spread(weo_subject_code, value) %>% 
  group_by(country) %>% 
  mutate(gross_gap = 1 + NGAP_NPGDP/100,
         gross_rate_gdp = 1 + NGDP_RPCH/100,
         gross_rate_potetial_gdp = gross_rate_gdp*dplyr::lag(gross_gap)/gross_gap,
         growth_potential_pct = 100*(gross_rate_potetial_gdp-1))


EU_AE_G7_tg_2003_2008 <- weo_cwide_EU_AE_G7 %>% 
  filter(year>=2003 & year <= 2008) %>% 
  summarise(avg_tg_2003_2008 = mean(growth_potential_pct))

EU_AE_G7_tg_2010_2016 <- weo_cwide_EU_AE_G7 %>% 
  filter(year>=2010 & year <= 2016) %>% 
  summarise(avg_tg_2010_2016 = mean(growth_potential_pct))

trend_growth_AE_G7_EU_2003_2008_2010_2016 <- left_join(EU_AE_G7_tg_2003_2008,
                                                       EU_AE_G7_tg_2010_2016,
                                              by = "country") %>% 
  mutate(dif = avg_tg_2010_2016-avg_tg_2003_2008)
  
real_gdp_gap_weo_long <-  weo_few %>% 
  filter(weo_subject_code %in% c("NGAP_NPGDP"))

real_gdp_wide <- real_gdp_long %>% 
  spread(key=year, value=value)

real_gdp_growth_wide <- real_gdp_growth_long %>% 
  spread(key=year, value=value)

real_gdp_gap_weo_wide <- real_gdp_gap_weo_long %>% 
  spread(key=year, value=value)
```

LAC-18, average trend growth for 2003-2008 and 2010-2016.
Source: real gdp from, WEO April 2017, and then HP filtered by author

```{r table_avg_tg_countries, echo=FALSE, results=TRUE}
uno_caption = "Average growth of potential output"
uno_colnames = c("país"," 2003-2008 ", " 2010-2016 ", " cambio ")
knitr::kable(trend_growth_2003_2008_2010_2016, digits = 1,
             col.names = uno_colnames, caption = uno_caption)
```


AEs, G7 and Euro zone, average trend growth for 2003-2008 and 2010-2016.
Source: real gdp growth and out gap from WEO April 2017, and potential gdp growth by author


```{r table_avg_tg_EUG7AE, echo=FALSE, results=TRUE}
trend_growth_AE_G7_EU_2003_2008_2010_2016[3,1] <- "G7"

knitr::kable(trend_growth_AE_G7_EU_2003_2008_2010_2016, digits = 1,
             col.names = uno_colnames, caption = uno_caption)
```

Combined table:

```{r table_avg_tg_combined, echo=FALSE, results=TRUE}
trend_growth_all_2003_2008_2010_2016 = bind_rows(
  trend_growth_2003_2008_2010_2016,
  trend_growth_AE_G7_EU_2003_2008_2010_2016)

knitr::kable(trend_growth_all_2003_2008_2010_2016, digits = 1,
             col.names = uno_colnames, caption = uno_caption,
             booktabs=TRUE)
```

```{r avg_tg_barplot_combined}
this_data <- trend_growth_all_2003_2008_2010_2016 %>% 
  mutate(country = factor(country),
         country = reorder(country, avg_tg_2003_2008)
         ) %>% 
  gather(key = period, value = avg_growth,
         avg_tg_2003_2008, avg_tg_2010_2016) %>% 
  mutate(period = factor(period, 
                         levels = c("avg_tg_2010_2016", 
                                    "avg_tg_2003_2008"))) %>% 
  arrange(country, period)


bp <- ggplot(this_data, aes(x = country, y = avg_growth, fill = period)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  coord_flip() + theme_minimal()



bp_t <- ggplot(this_data, aes(x = country, y = avg_growth, fill = period)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  coord_flip() + theme_tufte()

# bp
bp_t
```


LAC only:

```{r avg_tg_barplot_lac, fig.width=12, fig.height=12}
lac_data <- trend_growth_2003_2008_2010_2016 %>% 
  filter(!country %in% c("China", "United States"))  %>% 
  mutate(country = factor(country),
         country = reorder(country, avg_tg_2003_2008)
         ) %>% 
  gather(key = period, value = avg_growth,
         avg_tg_2003_2008, avg_tg_2010_2016) %>% 
  mutate(period = factor(period, 
                         levels = c("avg_tg_2010_2016", 
                                    "avg_tg_2003_2008"))) %>% 
  arrange(country, period)


bp_lac <- ggplot(lac_data, aes(x = country, y = avg_growth, fill = period)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  coord_flip() + ggtitle("Potential output growth, LAC") + 
  ylab("Average growth (%)") + xlab("") + 
  scale_fill_discrete(labels = c("2010 - 2016", "2003 - 2008")) +
  scale_y_continuous(breaks=seq(-2, 12, 2)) +
  theme_tufte() +
  theme(axis.text = element_text(size = 17),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 17),
        title = element_text(size = 19)) 

bp_lac
```

Selected economies:

```{r avg_tg_barplot_usachineg7euae}
not_lac_data <- trend_growth_all_2003_2008_2010_2016 %>% 
  filter(country %in% c("China", "United States", "G7",
                        "Euro area", "Advanced economies"))  %>% 
  mutate(country = factor(country),
         country = reorder(country, avg_tg_2003_2008)
         ) %>% 
  gather(key = period, value = avg_growth,
         avg_tg_2003_2008, avg_tg_2010_2016) %>% 
  mutate(period = factor(period, 
                         levels = c("avg_tg_2010_2016", 
                                    "avg_tg_2003_2008"))) %>% 
  arrange(country, period)


bp_not_lac <- ggplot(not_lac_data, aes(x = country, y = avg_growth, fill = period)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  coord_flip() + ggtitle("Potential output growth, not LAC") + 
  ylab("Average growth (%)") + xlab("") + 
  scale_fill_discrete(labels = c("2010 - 2016", "2003 - 2008")) +
  scale_y_continuous(breaks = seq(-2, 12, 2)) +
  theme_tufte()
# 
# bp_not_lac <- bp_not_lac +
#   theme(axis.text = element_text(size = 15),
#         legend.text = element_text(size = 15),
#         legend.title = element_text(size = 17),
#         title = element_text(size = 17)) 

bp_not_lac
```
